stages:
  - prepare
  - build
  - test


alpine-docker-build:
  image: docker:cli
  stage: prepare
  services:
    - docker:dind
  tags:
    - privileged
    - docker
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:alpine
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" -f ".gitlab-ci/Dockerfile.alpine" .
    - docker push "$DOCKER_IMAGE_NAME"
  rules:
    - changes:
      - .gitlab-ci/Dockerfile.alpine

.alpine-template:
  image: $CI_REGISTRY_IMAGE:alpine

alpine-build:
  stage: build
  extends: .alpine-template
  before_script:
    - mkdir -p build
    - cd build
  script:
    - cmake ..
    - cmake --build . --parallel $(nproc)
  artifacts:
    paths:
      - build/probarepp_test

alpine-test:
  stage: test
  extends: .alpine-template
  dependencies:
    - alpine-build
  script:
    - build/probarepp_test

